### ISSUE TITLE
Had to run npm install babel-preset-env to get this to work

### ISSUE THREAD

**Issue by shaunc869** [ratiw/vuetable-2-tutorial-bootstrap#10]
Not sure why, but I had to run:

npm install babel-preset-env

Otherwise I was getting a:

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vuetable-2/src/components/VuetablePaginationInfo.vue
Module build failed: Error: Couldn't find preset "env" relative to directory "/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/vuetable-2"
    at /Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-loader/lib/index.js:163:20)
 @ ./~/vuetable-2/src/components/VuetablePaginationInfo.vue 3:2-109

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vuetable-2/src/components/VuetablePagination.vue
Module build failed: Error: Couldn't find preset "env" relative to directory "/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/vuetable-2"
    at /Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-loader/lib/index.js:163:20)
 @ ./~/vuetable-2/src/components/VuetablePagination.vue 3:2-105

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vuetable-2/src/components/Vuetable.vue
Module build failed: Error: Couldn't find preset "env" relative to directory "/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/vuetable-2"
    at /Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/hackintosh/Downloads/vuetable-2-tutorial-bootstrap/node_modules/babel-loader/lib/index.js:163:20)
 @ ./~/vuetable-2/src/components/Vuetable.vue 7:2-95

Hope this helps!

**Comment by ratiw** [comment]
I haven't had time to update this repo. Thanks for posting this. :)

**Comment by jdriesen** [comment]
Same issue here ... :)
Looking forward to the update.

Grtz. Johnny (Belgium)
